#!/usr/bin/env bash

CONDAENV=`which ansible-playbook`

set -e

if [ "$CONDAENV" == "/opt/homebrew/Caskroom/micromamba/base/envs/algo/bin/ansible-playbook" ]; then
    echo "Conda algo environment active."
else
    echo "Activate Conda algo environment to run this script."
    exit
fi

#if [ -z ${VIRTUAL_ENV+x} ]
#then
#  ACTIVATE_SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.env/bin/activate"
#  if [ -f "$ACTIVATE_SCRIPT" ]
#  then
#    # shellcheck source=/dev/null
#    source "$ACTIVATE_SCRIPT"
#  else
#    echo "$ACTIVATE_SCRIPT not found.  Did you follow documentation to install dependencies?"
#    exit 1
#  fi
#fi

case "$1" in
  update-users) PLAYBOOK=users.yml; ARGS=( "${@:2}"  -t update-users ) ;;
  *) PLAYBOOK=main.yml; ARGS=( "${@}" ) ;;
esac

ansible-playbook ${PLAYBOOK} "${ARGS[@]}"
